---
title: "DAA_microbes_prevelance"
author: "Ming Yan"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: flatly
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```


# Load libraries
```{r}
library(tidyverse)
library(gtools) 
library(phyloseq)
library(data.table)
library(ggpubr)
```


# load data
```{r}
# metadata
metadata <- read.csv("/fs/ess/PAS0439/MING/virome_ecology/results/R_project/metadata_animal_performance.csv")

# microbiome daa
linda_species_out <- read.csv("/fs/ess/PAS0439/MING/virome_ecology/results/R_project/linda_species_out.csv")

prevelance <- read.csv("/fs/ess/PAS0439/MING/virome_ecology/results/R_project/microbe_species_prevelance_df.csv")

```


```{r}
linda_species_out_prevelance <- linda_species_out %>% left_join(prevelance[c("Species", "prevelance")], by =c("rowname" = "Species"))

linda_species_out_prevelance_full <- linda_species_out_prevelance %>% left_join(metadata[c("study", "liter", "trait")], by =c("project" = "study"))

core_common <- function(x){
  if (x == 100){
   return("100%")
  }
  else if (x >= 50){
    return("> 50%")
  }
  else if (x >= 20){
    return("> 20%")
  }
  else {
    return ("< 20%")
  }
}

plot_ready <- linda_species_out_prevelance_full %>% mutate(prevelance = sapply(prevelance, core_common)) %>% filter(padj < 0.1)


place_holder <- linda_species_out_prevelance_full %>% filter(!liter %in% unique(plot_ready$liter)) %>% group_by(project) %>% slice_min(padj) %>% unique() %>% ungroup()

place_holder <- place_holder %>% mutate(prevelance = sapply(prevelance, core_common))

plot_final <- rbind(plot_ready, place_holder)


plot_final[plot_final$project == "PRJEB23561","trait"] <- "Dietary composition (cattle)"
plot_final[plot_final$project == "PRJNA492173","trait"] <- "Dietary composition (goat)"


diet_study <- c("PRJEB21624", "PRJNA492173", "PRJEB23561")

plot_diet <- plot_final %>% filter(project %in% diet_study) %>% ggplot() + geom_point(aes(x = log2FoldChange, y = log10(padj), color = prevelance), size = 1) + 
  facet_wrap(vars(trait), scales = "free", labeller = function (labels) {   # reduce space between the facet legend 
               labels <- lapply(labels, as.character)           
               list(do.call(paste, c(labels, list(sep = "\n"))))
             })  +  scale_y_reverse() + geom_hline(yintercept=-1.3, linetype="dashed", 
                color = "red", size=1) + labs(y = "log10(q)") + 
  scale_color_discrete(name = "Prevelance") + theme_minimal() +
  theme(legend.position = "none") +
  labs(x = "")

plot_phenotype <- plot_final %>% filter(!project %in% diet_study) %>% ggplot() + geom_point(aes(x = log2FoldChange, y = log10(padj), color = prevelance), size = 1) + 
  facet_wrap(vars(trait), scales = "free", labeller = function (labels) {   # reduce space between the facet legend 
               labels <- lapply(labels, as.character)           
               list(do.call(paste, c(labels, list(sep = "\n"))))
             })  +  scale_y_reverse() + geom_hline(yintercept=-1.3, linetype="dashed", 
                color = "red", size=1) + labs(y = "log10(q)") + 
  scale_color_discrete(name = "Prevelance") + theme_minimal() +
  theme(legend.position = "bottom") 

plot_daa <- ggarrange(plot_diet, plot_phenotype, nrow = 2, heights = c(1, 2))

plot_daa
ggsave("/fs/ess/PAS0439/MING/virome_ecology/results/R_project/daa_volcano.png", width = 9, height = 6, dpi = 700)
```

# session info
```{r}
sessionInfo()
```