---
title: "virome_ecology"
author: "Ming Yan"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: flatly
    code_download: true
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

# Load libraies

```{r}
library(tidyverse)
library(vegan)
library(ggpubr)
library(rstatix)
```


# stats
```{r}
micro = read_csv("/fs/ess/PAS0439/MING/virome_ecology/results/inStrain_RVD/micro_diversity.csv")
Studies <- factor(unique(micro$study))
micro_ready_performance <- micro %>% arrange(study,animal, treatment) %>% 
  mutate(treatment= factor(treatment, levels = c("High", "Medium", "Low", "HLS", "LLS", "Grazing", "TMR", "Basal", "NFC", "Protein", "Healthy", "SARA")))

stat.performance <- micro_ready_performance %>%
  group_by(liter) %>%
  wilcox_test(average_micro_diversity ~ treatment) %>%
  add_significance("p")

## For Li et al. comparison only performed within beef and dairy

stat.performance <- stat.performance %>% filter(!(group1 == "HLS" & group2 == "Grazing")) %>% 
  filter(!(group1 == "LLS" & group2 == "Grazing"))  %>% 
  filter(!(group1 == "HLS" & group2 == "TMR"))  %>% 
  filter(!(group1 == "LLS" & group2 == "TMR")) %>% inner_join(unique(micro[,c("liter", "trait")]), by = "liter")


```

### Comparing micro diversity among different animal performance traits. 
```{r}
diet_study <- c("PRJEB21624", "PRJNA492173", "PRJEB23561")

species_color <- c("#e03f34", "#24b1ed", "#e13bed", "#24ed67")
names(species_color) <- c("Beef", "Dairy", "Sheep", "Goat")

p <- micro_ready_performance %>% ggplot() + 
  aes(x=treatment, y= average_micro_diversity) + geom_boxplot(aes(color = animal))+
    theme(legend.position = "bottom") + labs(color = "Species") + 
  scale_color_manual(name = "Species", values = species_color)+
  theme(text = element_text(size=8))   

micro_legend <- get_legend(p)

micro_ready_performance[micro_ready_performance$study == "PRJEB23561","trait"] <- "Dietary composition (cattle)"
micro_ready_performance[micro_ready_performance$study == "PRJNA492173","trait"] <- "Dietary composition (goat)"

micro_box_diet <- micro_ready_performance %>% filter(study %in% diet_study) %>% ggplot() + 
  aes(x=treatment, y= average_micro_diversity) + geom_boxplot(aes(color = animal)) +
  facet_wrap(vars(trait), scales = "free", labeller = function (labels) {   # reduce space between the facet legend 
               labels <- lapply(labels, as.character)           
               list(do.call(paste, c(labels, list(sep = "\n"))))
             }) + 
  labs(x = "", y = expression("Micro-diversity ("*pi*")")) +  labs(color = "Species") +
  geom_jitter(size = 0.8, width = 0.2,  aes(color = animal)) +
  theme_minimal()+
    theme(legend.position = "none") + 
  scale_color_manual(name = "animal", values = species_color)

micro_box_diet

```

```{r}
micro_box_phenotype <- micro_ready_performance %>% filter(!study %in% diet_study) %>% ggplot() + 
  aes(x=treatment, y= average_micro_diversity) + geom_boxplot(aes(color = animal)) +
  facet_wrap(vars(trait), scales = "free", labeller = function (labels) {   # reduce space between the facet legend 
               labels <- lapply(labels, as.character)           
               list(do.call(paste, c(labels, list(sep = "\n"))))
             }) + 
  labs(x = "", y = expression("Micro-diversity ("*pi*")")) +  labs(color = "Species") +
  geom_jitter(size = 0.8, width = 0.2, aes(color = animal)) + 
  scale_y_continuous(expand = expansion(mult = c(0, 0.15)))  + 
  theme_minimal()+
    theme(legend.position = "none") + 
  scale_color_manual(name = "animal", values = species_color) 

micro_box_phenotype



```

```{r}
## add annotations when significant
micro_box_diet_anno <- micro_box_diet +
   geom_curve(data=tibble(trait = "Concentrate level"), aes(x=1, xend=2, y=0.013, yend=0.013), curvature = -0.1) +
  geom_text(data=tibble(trait = "Concentrate level"), aes(x=1.5, y=0.0135, label = "***" ), size=3) + 
  geom_curve(data=tibble(trait = "Dietary composition (goat)"), aes(x=1, xend=3, y=0.0063, yend=0.0063), curvature = -0.1) +
  geom_text(data=tibble(trait = "Dietary composition (goat)"), aes(x=2, y=0.0065, label = "***" ), size=3) + 
  geom_curve(data=tibble(trait = "Dietary composition (goat)"), aes(x=2, xend=3, y=0.005, yend=0.005), curvature = -0.1) +
  geom_text(data=tibble(trait = "Dietary composition (goat)"), aes(x=2.5, y=0.00515, label = "**" ), size=3) +
   geom_curve(data=tibble(trait = "Dietary composition (goat)"), aes(x=1, xend=2, y=0.006, yend=0.006), curvature = -0.1) +
  geom_text(data=tibble(trait = "Dietary composition (goat)"), aes(x=1.5, y=0.00615, label = "***" ), size=3) +
  geom_curve(data=tibble(trait = "Dietary composition (cattle)"), aes(x=3, xend=4, y=0.0075, yend=0.0075), curvature = -0.1) +
  geom_text(data=tibble(trait = "Dietary composition (cattle)"), aes(x=3.5, y=0.0078, label = "*" ), size=3) +
  theme(text = element_text(size=8)) +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))

svg("/fs/ess/PAS0439/MING/virome_ecology/results/inStrain_RVD/virome_micro_diet.svg", width = 5, height = 1.6)
micro_box_diet_anno 
dev.off()

```

```{r}
micro_box_phenotype_anno <- micro_box_phenotype +
  geom_curve(data=tibble(trait = "Methane emission"), aes(x=1, xend=2, y=0.0082, yend=0.0082), curvature = -0.1) +
  geom_text(data=tibble(trait = "Methane emission"), aes(x=1.5, y=0.00835, label = "*" ), size=3) +
  geom_curve(data=tibble(trait = "Milk protein yield"), aes(x=1, xend=2, y=0.0215, yend=0.0215), curvature = -0.1) +
  geom_text(data=tibble(trait = "Milk protein yield"), aes(x=1.5, y=0.0225, label = "**" ), size=3) +
  theme(text = element_text(size=8))  +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm")) 

svg("/fs/ess/PAS0439/MING/virome_ecology/results/inStrain_RVD/virome_micro_pheno.svg", width = 5, height = 2.5)
micro_box_phenotype_anno
dev.off()
```

```{r}
ggarrange(micro_legend, nrow = 1, heights = 1)
ggsave("/fs/ess/PAS0439/MING/virome_ecology/results/inStrain_RVD/virome_micro_legend.svg", width = 5, height = 1)
```
```